// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TP02SWII6.Models;

#nullable disable

namespace TP02SWII6.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241012210854_CreateContainerTable")]
    partial class CreateContainerTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TP02SWII6.Models.BL", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Consignee")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("consignee");

                    b.Property<string>("Navio")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("navio");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("numero");

                    b.HasKey("Id");

                    b.ToTable("bl");
                });

            modelBuilder.Entity("TP02SWII6.Models.Container", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BLId")
                        .HasColumnType("int");

                    b.Property<int>("IdBL")
                        .HasColumnType("int")
                        .HasColumnName("idBL");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("numero");

                    b.Property<int>("Tamanho")
                        .HasColumnType("int")
                        .HasColumnName("tamanho");

                    b.Property<int>("Tipo")
                        .HasColumnType("int")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("BLId");

                    b.HasIndex("IdBL");

                    b.ToTable("container");
                });

            modelBuilder.Entity("TP02SWII6.Models.Container", b =>
                {
                    b.HasOne("TP02SWII6.Models.BL", null)
                        .WithMany("Containers")
                        .HasForeignKey("BLId");

                    b.HasOne("TP02SWII6.Models.BL", null)
                        .WithMany()
                        .HasForeignKey("IdBL")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_BL_Container");
                });

            modelBuilder.Entity("TP02SWII6.Models.BL", b =>
                {
                    b.Navigation("Containers");
                });
#pragma warning restore 612, 618
        }
    }
}
